### ISSUE TITLE
Create a Pull Request Template

### ISSUE THREAD

**Issue by armudgal** [IEEE-VIT/techloop-ml-plus#2]
Need someone to create a PR Template which will help us to regulate what are the necessities in the PR submitted by juniors.

**Comment by anubis-me** [comment]
Done by Raj.

**Comment by armudgal** [comment]
Pull request template is a diff thing. Read about it, you nedd to create a seperate file like `PULL_REQUEST.TEMPLATE`

**Comment by armudgal** [comment]
@IEEE-VIT/mentors Take a look at this, get this done ASAP.

**Comment by armudgal** [comment]
Good work @Sushanti99 :)
